apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-system
  namespace: development
  labels:
    app: notification-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-system
  template:
    metadata:
      labels:
        app: notification-system
    spec:
      containers:
        - name: notification-system
          image: notification-system:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: notification-system-config
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
