apiVersion: v1
kind: Service
metadata:
  name: notification-system
  namespace: development
  labels:
    app: notification-system
spec:
  type: NodePort
  selector:
    app: notification-system
  ports:
    - name: http
      port: 8081
      targetPort: 8081
